spring:
  application:
    name: business-login
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 120.24.149.53:8848

dubbo:
  scan:
    base-packages: com.hyorin.myshop.plus.business.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://120.24.149.53:8848

server:
  # ${random.int[9000,9999]} 随机端口
  port: 9900

management:
  endpoints:
    web:
      exposure:
        include: "*"

business:
  oauth2:
    grant_type: password
    client_secret: secret
    client_id: client